modLoader="javafml"
loaderVersion="[47,)"
license="MIT License https://github.com/McJtyMods/ParsMinima/blob/1.18/LICENCE"
issueTrackerURL="http://github.com/McJtyMods/ParsMinima/issues"
displayURL="http://github.com/McJtyMods/ParsMinima/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mods]]
modId="parsminima"
version="${file.jarVersion}"
displayName="ParsMinima"
#updateJSONURL="http://myurl.me/" #optional
description='''
Microblocks!
'''
[[dependencies.parsminima]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.0,)"
    ordering="NONE"
    side="BOTH"
